- web/package-lock.json
Update package-lock.json because `make install-frontend-ci` is failing.
Error is below:
```
cd web && npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```
> Update package-lock.json because `make install-frontend-ci` is failing.

- Makefile
make deploy: build and push an image, then deploy with helm.
Make variables REGISTRY_ORG and TAG control the image used.
> Add 'make deploy' target to simplify testing with local cluster.

- web/src/korrel8r-client.ts
Remove `class: alert:alert` from the client request.
Having a fixed class limits the panel to queries starting at an alert.
Korrel8r can deduce the class from the query, so it is not needed.
> Allow any korrel8r query in panel.

- web/src/components/Korrel8rPanel.tsx
Resolves #18.
Adds a comparison check around the onClick function call to prevent the data from being cleared if the query stays the same. 
Also renamed query => savedQuery and queryString to queryInputField since their names were ambiguous.
Conflicts with #19 so either this or #19 will need a rebase after merging.
> Prevent clearing unchanged query result & rename query variables to make them more clear

- web/src/components/Korrel8rPanel.tsx
- web/src/hooks/usePluginAvailable.ts
Resolves #17.
Adds loading status to usePluginAvailable, which is then used to prevent the primary korrel8r query until they have finished running.
Refactored the primary useEffect since it was getting very large with a lot of dependencies. I also tried to use a reducer instead but I found the resulting code to be confusing and that it clashes too much with redux. All of the state could be moved into redux to make everything flow through the same reducer, but we are trying to move off of redux going forward and adding extra project logic to redux seemed like a poor idea with that in mind.
I messed up the rebasing the changes from #20 onto #19, so I'm reopening this with a clean/correct git history.
> Prevent extra Korrel8r API calls

- web/src/components/Korrel8rPanel.tsx
Moving the preventQuery and clearError outside of the useEffect or any useMemo and useCallback's prevents the state from being updated correctly, leaving the Korrel8r API to never get called.
Here we are moving the state back into the useEffect since it't not a large enough code migration to break out the useMemo and useCallbacks
> Move the react state changes back inside the use effect to prevent the query from not being triggered

- web/src/hooks/useTroubleshootingPanel.tsx
- web/src/hooks/useURLState.ts
The action creation uses the key 'alert-detail-toolbar-actions' to add add the "Troubleshooting Panel" button to the alerts detail page. However, the developer perspective also uses that key to retrieve actions. This led to an unexpected URL being parsed, causing an uncaught error.
This PR looks to prevent an uncaught error and prevent the developer perspective from having access to the troubleshooting panel button.
It also refactors two useState's + a useEffect into two useMemo's since they are only being used as computed values.
Of note this PR adds a console.error whenever the URL fails to get parsed, which may be incorrect. I can see the value in knowing why something failed when trying to debug, but also it may be providing extraneous information and filling up the console with …
> OU-455: Prevent uncaught error and usage in developer perspective

- web/src/components/Korrel8rTopology.tsx
- web/src/korrel8r/k8s.ts
When manually creating a netflow query, it returns a Kubernetes Node as one of the nodes in the correlation graph. When we query for the the kubernetes node [GVK](https://book.kubebuilder.io/cronjob-tutorial/gvks.html) there are two separate GVK's that are returned. The old code had previously interpreted this as a failure to parse the query, and then placed a null in the array which then threw an error when the id parameter was retrieved from it.
This PR adds two seperate changes:
1. Use the first GVK returned if multiple are returned
2. Skip nodes that fail to be parsed. Then skip edges for these skipped nodes.
> OU-457: Fix Netflow Class Korrel8r Queries

- web/src/__tests__/netflow-node.spec.ts
- web/src/components/Korrel8rTopology.tsx
- web/src/korrel8r/netflow.ts
The Netflow URL's generated from the Korrel8r queries are missing the filter query parameter. The Korrel8r query is only a logql query and can be parsed simply, but before #27 can be merged, the filters => Korrel8r query transformation will need to be looked at, as they have a complex query language built into their filters, much of which Korrel8r doesn't support. 
The selected node check added another loop to prevent extra parameters added by a page from stopping a match. For example, if the page adds an additional query parameter of `timeRange` the logic will now still be able to match and highlight the node
> OU-457: Update Netflow URL to add filter query parameter

- Makefile
- README.md
- web/src/components/Korrel8rPanel.tsx
- web/src/components/Popover.tsx
- web/src/hooks/useTroubleshootingPanel.tsx
- web/src/redux-actions.ts
- web/src/redux-reducers.ts
See https://issues.redhat.com/browse/OU-476
Repeating the same query gave different results, sometimes success, sometimes a JSON parsing error.
Refactored Korrle8rPanel logic to simplify and remove race conditions:
- No props passed to Korrle8rPanel, initialize from context URL.
- useState only for query and result, no redux or dispatch. There is no need to share state with other components.
- Single atomic state variable for result: holds graph or error.
- Don't check other plugin availability, let korrel8r determine what is available at runtime.
- Don't filter results, assume korrel8r will return correct results.
- Always run query even if it hasn't changed - simpler logic + the cluster state may have changed.
> fix(OU-467): refactor and simplify panel logic to fix races

- web/locales/en/plugin__troubleshooting-panel-console-plugin.json
- web/src/components/Korrel8rPanel.tsx
feat: add "Focus" button to re-start correlation from current URL. #27
Focus button allows two-sided navigation between panel and main console window:
Workflow:
- Open panel (e.g. on an alert screen) shows data correlated to that alert.
- Navigate to other console screens
- by clicking on nodes in the correlation graph
- by using any other console links
- Click "Focus" to re-compute the graph, starting from resources in the current console screen.
> feat: add "Focus" button re-calculates correlation from current URL.

- web/locales/en/plugin__troubleshooting-panel-console-plugin.json
- web/src/components/Korrel8rPanel.tsx
- web/src/components/Popover.tsx
- web/src/korrel8r-client.ts
- web/src/korrel8r/query.types.ts
Add controls to:
- show/hide query details
- choose neighbour or goal search
- specify depth or goal class
> feat: Advanced query controls, fixes #40

- web/console-extensions.json
- web/package.json
- web/src/components/NullContextProvider.tsx
- web/src/hooks/usePopover.tsx
- web/src/hooks/useTroubleshootingPanel.tsx
- web/src/redux-reducers.ts
This PR will allow the console to trigger the panel just by dispatching the `openTP` action with redux. This will allow to trigger the panel globally from the masthead menu.
> OU-484: Allow the troubleshooting panel to be triggered globally from the console

- web/src/__tests__/alert-node.spec.ts
- web/src/__tests__/k8s-node.spec.ts
- web/src/__tests__/log-node.spec.ts
- web/src/__tests__/netflow-node.spec.ts
- web/src/korrel8r/alert.ts
- web/src/korrel8r/log.ts
- web/src/korrel8r/metric.ts
- web/src/korrel8r/netflow.ts
- web/src/korrel8r/query-url.ts
- Netflow URL format seems to have changed, there is no longer a q= parameter.
- Fixed URL encoding parameter issues.
- Updated error messages to be more consistent.
- Support pod aggregated log URLs.
- Simplify log conversions.
NOTE: already reviewed as https://github.com/openshift/troubleshooting-panel-console-plugin/pull/50
which was closed by mistake.
> fix: log and netflow query-URL conversion

- web/src/components/Korrel8rPanel.tsx
Previously was showing empty for a graph with a single node and  no edges.
> fix(#66): Show single node graphs.

- web/src/korrel8r-client.ts
This PR adds a validation before trimming a query that can be undefined. This will prevent errors when opening the panel from views in which the URL does not produce a korrel8r query
> OU-564: add query validation before trimming

- web/src/components/Korrel8rPanel.tsx
- web/src/components/topology/Korrel8rTopology.tsx
- web/src/hooks/useTroubleshootingPanel.tsx
- web/src/korrel8r-client.ts
- web/src/redux-actions.ts
- web/src/redux-reducers.ts
This PR looks to persist the korrel8r query information in the store to allow users to close and open the panel without losing track of where their old query was. 
Of note, because the store is reinstantiated each time a tab is opened, this won't persist the query when refreshing or opening the console at a later time. I think this is a fine tradeoff which clears away the issue of stale queries. If we want persistence through new tabs and refreshing, we will need to store in the browser storage instead.
The swap of query to an object does lead to a decent amount of spreading the old object out then overriding only one of the fields, but it feels to the point and expressive so I think its fine.
> OU-537: Persist Query Information between closing and opening

- web/src/korrel8r/node-factory.ts
When using an Array.forEach loop, returns in the function will only return the inner function, not the context calling forEach. This PR converts the Array.forEach into a for ... of loop so that the correctly parsed node is returned correctly.
> NO-JIRA: Fix an issue which never returned a node

- Makefile
- web/src/__tests__/node-factory.spec.ts
- web/src/__tests__/trace-node.spec.ts
- web/src/korrel8r/trace.ts
- web/tsconfig.json
Manual cherry pick of #96 
- Map trace-ID URLs to trace:id queries.
- Add "select" set for common attributes.
> Manual cherry pick for #96

- web/package-lock.json
- web/package.json
- web/src/components/topology/Korrel8rTopology.tsx
- web/src/hooks/useQueryParams.ts
- web/src/hooks/useURLState.ts
remove react-router and react-router-dom to be replaced by react-router-dom-compat-v5 for transition to react-router v6
https://github.com/openshift/console/pull/14957
Slack #observability-ui-interal thread
https://redhat-internal.slack.com/archives/C03EPFR2BAR/p1744392852882399
Slack #announce-console-plugins
https://redhat-internal.slack.com/archives/C032NLNEE8G/p1744391666020899
> NO-JIRA: replace react-router* with react-router-dom-v5-compat

- .gitignore
- Dockerfile.devspace
- Makefile
- README.md
- devspace.yaml
- devspace_start.sh
This PR looks to add in-cluster development of plugins using [devspace](https://www.devspace.sh/). It will take over an existing troubleshooting panel deployment from COO and copy the changes that the webpack dev server makes on your local machine up into the cluster. This prevents having to run korrel8r and other plugins locally and should simplify development.
https://github.com/user-attachments/assets/9bae9808-86f4-47d5-a223-0f7ec9748469
> NO-JIRA: add incluster development of UI plugin using devspace

- Dockerfile.cypress
This PR looks to add a containerfile which will run the cypress unit tests. Once this file has been added the prow config can be update to build and run it
> NO-JIRA: add unit test containerfile

- web/src/components/Popover.tsx
This PR looks to close the troubleshooting panel when swapping to a non-admin perspective, as well as prevent its opening in the first place.
https://github.com/user-attachments/assets/ac68ec3c-d72b-4d3a-9142-ca5e4ba03518
> OU-771: close tp in non-admin perspectives
